/**
 * What: the rail. Quiet years still get a sentence. History is the golden path.
 * Why: finance runs away in books that get harder to unwind.
 */
import type { Card, Choice, FactionId } from "./types.ts";

export const FIRST_CARD_ID = "volcker-1979";
export const EASTER_EGG_CARD_ID = "three-six-three";

const ROOM: readonly FactionId[] = [
  "irgc",
  "leader",
  "street",
  "my_party",
  "opposing_party",
  "media",
  "cia",
  "saudis",
  "europeans",
  "china",
  "venezuela",
];

function hindsight(story: string): Pick<Choice, "overlay" | "resultTitle" | "result"> {
  return {
    overlay: "hindsight",
    resultTitle: "Yes. That was the right thing to do.",
    result: `${story}\n\nThat is not what happened. Hindsight is 20/20. You have the point. The book continues on.`,
  };
}

function drive(where: string): Pick<Choice, "overlay" | "resultTitle" | "result"> {
  return hindsight(
    `You left the cubicle. You drove to ${where}. The invoice was a parking lot, or a warehouse that emptied at night, or a house nobody lived in. Enron passed every audit. So did Crazy Eddie. People committing financial crimes are accountants. Auditors are also accountants. Accountants know how to lie to other accountants. To catch a criminal you have to leave your cubicle and drive to the address on the invoice.`,
  );
}

function moral(story: string): Pick<Choice, "epilogue" | "overlay" | "resultTitle" | "result"> {
  return {
    epilogue: true,
    overlay: "moral",
    resultTitle: "We congratulate you on your moral choice.",
    result: `${story}\n\nIt is a moral victory. The machinery grinds on. You left. A stick figure sits the desk. The Street continues.`,
  };
}

function serve(title: string, body: string): Pick<Choice, "overlay" | "resultTitle" | "result"> {
  return { overlay: "serve", resultTitle: title, result: body };
}

function adapts(title: string, body: string): Pick<Choice, "overlay" | "resultTitle" | "result"> {
  return { overlay: "adapts", resultTitle: title, result: body };
}

const CARDS: Card[] = [
  {
    id: "volcker-1979",
    year: 1979,
    yearLabel: "1979",
    title: "The spread is dead",
    titleUs: "Volcker hikes",
    titleIran: "The 3-6-3 world ends",
    era: "sl",
    status: "playable",
    branchPoint: true,
    referee: {
      paragraphs: [
        "Thrifts borrow short and lend long. That was the business. Volcker is killing inflation by killing the spread. The book is already underwater. Nobody has driven to the loans yet.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "Inflation is the emergency. The thrifts are a sector. I hike until it breaks. The duration gap is their problem.",
        closer: "Paul Volcker. He is in the room. He is not the chair.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "Thirty-year mortgages at six. Deposits that now want eleven. The audit still shows a thrift. The audit is a cubicle.",
      },
    ],
    situationUs:
      "You are Carter. Volcker wants the hike. The thrifts will scream. Inflation is already a street bar.",
    situationIran:
      "You are a savings and loan. Borrow at 3, lend at 6, on the golf course by 3. That world is over this afternoon if he hikes.",
    iranChoices: [
      {
        id: "ir-keep-30s",
        label: "Keep originating 30-years",
        summary: "The book you know.",
        kind: "soft",
        historical: true,
        deltas: { irgc: -6, liberals: 8, street: 4 },
      },
      {
        id: "ir-stop-30s",
        label: "Stop the 30-years",
        summary: "Mark the duration now.",
        kind: "hard",
        deltas: { irgc: 4, street: -8, leader: -4 },
        ...hindsight("You stopped originating the duration bomb. The sector did not."),
      },
    ],
    usChoices: [
      {
        id: "us-hike",
        label: "Let Volcker hike",
        summary: "Inflation first.",
        kind: "hard",
        historical: true,
        deltas: { cia: 8, street: -10, my_party: -6, liberals: 10, europeans: -4 },
      },
      {
        id: "us-blink",
        label: "Blink",
        summary: "The thrifts have senators.",
        kind: "soft",
        deltas: { cia: -12, saudis: 6, street: 4, liberals: -4 },
        ...serve("The Fed still hikes", "Volcker has the guns on rates. You blinked on letterhead. The hike still happens. You serve the chair's fear of the thrift lobby. The rail continues on."),
      },
    ],
    sources: ["Volcker 1979 Saturday night special", "3-6-3 banking"],
    visibleFactions: ROOM,
    next: "didmca-1980",
  },
  {
    id: "didmca-1980",
    year: 1980,
    yearLabel: "1980",
    title: "The put gets a bigger number",
    titleUs: "Insurance to $100,000",
    titleIran: "Brokered deposits",
    era: "sl",
    status: "playable",
    electionYear: true,
    referee: {
      paragraphs: [
        "DIDMCA. Deposit insurance to $100,000. Rate caps begin to die. The put is now large enough to fund a gamble.",
      ],
      tags: ["LT"],
    },
    briefings: [
      {
        faction: "europeans",
        audience: "us",
        rant: "Raise the cap or watch a run. The fund is not built for this. Raise it anyway.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "Insured deposits at any price. Then lend them at a hope. The cubicle will call that growth.",
      },
    ],
    situationUs: "Carter year. Raise the insurance cap. The thrifts say it is the only way they live.",
    situationIran: "The cap goes to $100k. You can buy deposits from a broker now. The duration hole is still there.",
    iranChoices: [
      {
        id: "ir-buy-brokered",
        label: "Buy the brokered deposits",
        summary: "Grow out of the hole.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -4, europeans: -6, leader: 4 },
      },
      {
        id: "ir-stay-small",
        label: "Stay small",
        summary: "Do not fund the gamble.",
        kind: "walk",
        deltas: { irgc: 6, leader: -6 },
        ...hindsight("You did not buy the put. The sector did."),
      },
    ],
    usChoices: [
      {
        id: "us-raise-cap",
        label: "Raise the cap",
        summary: "DIDMCA.",
        kind: "deal",
        historical: true,
        deltas: { europeans: -8, street: 6, saudis: 4, my_party: 4 },
      },
      {
        id: "us-keep-cap",
        label: "Keep the cap at $40,000",
        summary: "Do not enlarge the put.",
        kind: "hard",
        deltas: { europeans: 4, street: -8, my_party: -8 },
        ...hindsight("The put stayed small. The zombies would have had less to gamble with."),
      },
    ],
    sources: ["DIDMCA 1980"],
    visibleFactions: ROOM,
    next: "garn-1982",
  },
  {
    id: "garn-1982",
    year: 1982,
    yearLabel: "1982",
    title: "Let them grow out of it",
    titleUs: "To forbear or not to forbear",
    titleIran: "Danger: zombies",
    era: "sl",
    status: "playable",
    branchPoint: true,
    referee: {
      paragraphs: [
        "Garn-St Germain. Adjustable mortgages. Commercial loans. Junk. The insolvent are told to grow out of the hole. FSLIC will pay if they do not. This is Ajax. It works, until it does not.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "saudis",
        audience: "us",
        rant: "Close them now and you own a recession in an election year. Forbear. They will grow out.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "The old book is dead. The new book is anything a cubicle will mark. Desert condos. Junk. The audit will pass. Audits pass.",
      },
    ],
    situationUs:
      "Reagan sits. The bill is on the desk. Close the insolvent now, or let them grow out of it. Growing out of it is the cable everyone wants.",
    situationIran:
      "They are about to let you buy junk and condos with insured deposits. The duration hole is still there. The cubicle is about to call the hole a strategy.",
    iranChoices: [
      {
        id: "ir-gamble",
        label: "Gamble for resurrection",
        summary: "Junk, condos, brokered deposits.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -8, leader: 8, europeans: -6, venezuela: 4 },
      },
      {
        id: "ir-close-self",
        label: "Hand the keys to FSLIC",
        summary: "Admit the hole.",
        kind: "walk",
        deltas: { irgc: 10, leader: -20, street: -4 },
        ...moral("You handed the keys over. The sector did not. A replacement sits. The Street continues."),
      },
    ],
    usChoices: [
      {
        id: "us-garn",
        label: "Let them grow out of it",
        summary: "Garn-St Germain.",
        kind: "deal",
        historical: true,
        deltas: { europeans: -10, saudis: 6, street: 4, liberals: 12, irgc: -4 },
        flags: { s_l_worked: false },
      },
      {
        id: "us-close-now",
        label: "Close the insolvent now",
        summary: "No zombies.",
        kind: "hard",
        deltas: { europeans: 8, saudis: -12, my_party: -10, street: -6, liberals: -20 },
        ...hindsight("You closed the zombies in 1982. The bill stayed a 1982 bill. The RTC was not a 1990s novel."),
      },
    ],
    sources: ["Garn-St Germain Depository Institutions Act 1982"],
    visibleFactions: ROOM,
    next: "lincoln-1984",
  },
  {
    id: "lincoln-1984",
    year: 1984,
    yearLabel: "1984",
    title: "Lincoln",
    titleUs: "Keating buys a thrift",
    titleIran: "You buy Lincoln",
    era: "sl",
    status: "playable",
    electionYear: true,
    referee: {
      paragraphs: [
        "Charles Keating takes Lincoln Savings. Brokered deposits. Junk. Arizona dirt. The cubicle at the FHLBB is about to get a letter from five senators.",
      ],
      tags: ["LT"],
    },
    briefings: [
      {
        faction: "leader",
        audience: "iran",
        rant: "Lincoln is a platform. Insured deposits in, desert out. The audit will pass until it cannot.",
        face: "keating",
      },
      {
        faction: "saudis",
        audience: "us",
        rant: "A constituent with a thrift. Do not let the San Francisco examiners get ahead of themselves.",
      },
    ],
    situationUs: "A Phoenix developer just bought a California thrift. The examiners are twitchy. The senators will call.",
    situationIran: "You bought Lincoln. The old 3-6-3 men are gone. The book is about to become a story.",
    iranChoices: [
      {
        id: "ir-lincoln-grow",
        label: "Grow it tenfold",
        summary: "Brokered deposits. Junk. Dirt.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -10, leader: 10, europeans: -8, venezuela: 6 },
        flags: { iran_face: "keating" },
      },
      {
        id: "ir-lincoln-mortgages",
        label: "Stay in mortgages",
        summary: "The boring book.",
        kind: "soft",
        deltas: { irgc: 6, leader: -8 },
        ...hindsight("Lincoln stayed a thrift. Keating stayed a developer. The cubicle had less to lie about."),
      },
    ],
    usChoices: [
      {
        id: "us-watch-lincoln",
        label: "Watch Lincoln",
        summary: "The examiners can wait.",
        kind: "ignore",
        historical: true,
        deltas: { europeans: -4, saudis: 4, media: -2 },
      },
      {
        id: "us-seize-lincoln",
        label: "Seize Lincoln now",
        summary: "1984, not 1989.",
        kind: "hard",
        deltas: { europeans: 6, saudis: -10, my_party: -6 },
        ...hindsight("You seized Lincoln in 1984. The Keating Five never sat. The bill stayed a 1984 bill."),
      },
    ],
    sources: ["Lincoln Savings, Keating 1984"],
    visibleFactions: ROOM,
    next: "eddie-1987",
  },
  {
    id: "eddie-1987",
    year: 1987,
    yearLabel: "1987",
    title: "The carnival",
    titleUs: "Crazy Eddie passed the audit",
    titleIran: "Drive to the warehouse",
    era: "sl",
    status: "playable",
    referee: {
      paragraphs: [
        "Crazy Eddie. Electronics. Inventory that travels at night between stores ahead of the auditors. The carnival. The audit passed. Enron's audit will pass. The cubicle is not a detective.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "venezuela",
        audience: "us",
        rant: "The financials are clean. We signed them. We did not drive to Brooklyn at 2 a.m.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "The warehouse is empty when the auditors leave. Full when they arrive. Accountants lying to accountants. That is the book.",
      },
    ],
    situationUs:
      "A retailer just became a case file. The audit passed. Every year. The invoices have addresses. Nobody from your chair has seen the loading dock.",
    situationIran:
      "You are not Crazy Eddie. You are the thrift next door, watching a retailer teach the lesson. The auditors will come to you the same way. They will not drive at night.",
    actionPrompt: "Do you leave the cubicle?",
    iranChoices: [
      {
        id: "ir-trust-audit",
        label: "Trust the audit",
        summary: "The cubicle is the job.",
        kind: "soft",
        historical: true,
        deltas: { irgc: -4, drone_holes_known: -2, venezuela: 4 },
      },
      {
        id: "ir-drive-warehouse",
        label: "Drive to the warehouse at night",
        summary: "The address on the invoice.",
        kind: "hard",
        deltas: { irgc: 6, drone_holes_known: 20, leader: -4 },
        ...drive("the warehouse at 2 a.m."),
      },
    ],
    usChoices: [
      {
        id: "us-trust-eddie",
        label: "The audit passed",
        summary: "SEC has the filing.",
        kind: "ignore",
        historical: true,
        deltas: { venezuela: 4, drone_holes_known: -2, media: 2 },
      },
      {
        id: "us-drive-eddie",
        label: "Send someone to the loading dock",
        summary: "Leave the cubicle.",
        kind: "covert",
        deltas: { drone_holes_known: 20, venezuela: -8, media: 6 },
        ...drive("the Crazy Eddie warehouse"),
      },
    ],
    sources: ["Crazy Eddie fraud, Sam Antar, inventory carnival"],
    visibleFactions: ROOM,
    next: "keating-1987",
  },
  {
    id: "keating-1987",
    year: 1987,
    yearLabel: "1987",
    title: "The five",
    titleUs: "Keating Five",
    titleIran: "Call the senators",
    era: "sl",
    status: "playable",
    referee: {
      paragraphs: [
        "Five senators. A million in donations. San Francisco wants to seize Lincoln. The senators want the examiners to forbear. FSLIC is already insolvent. Forbearance is how the bill grows.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "saudis",
        audience: "us",
        rant: "These are constituents. The examiners are cowboys. Give Lincoln time.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "Call Washington. The cubicle in San Francisco does not understand Arizona dirt.",
        face: "keating",
      },
    ],
    situationUs: "Five of yours took the meeting. The examiners want Lincoln. The fund is already empty.",
    situationIran: "The examiners are at the door. You have senators. That is a product.",
    iranChoices: [
      {
        id: "ir-call-five",
        label: "Call the five",
        summary: "Forbearance is the product.",
        kind: "covert",
        historical: true,
        deltas: { saudis: 8, europeans: -10, irgc: -6, media: -4 },
      },
      {
        id: "ir-take-exam",
        label: "Take the exam",
        summary: "Let them see the dirt.",
        kind: "walk",
        deltas: { europeans: 6, leader: -12, irgc: 4 },
        ...hindsight("You let the examiners in. Lincoln closed smaller. The five never sat."),
      },
    ],
    usChoices: [
      {
        id: "us-forbear",
        label: "Forbear",
        summary: "The five have spoken.",
        kind: "soft",
        historical: true,
        deltas: { saudis: 6, europeans: -8, media: -6, my_party: 2 },
      },
      {
        id: "us-seize-87",
        label: "Seize Lincoln anyway",
        summary: "The fund is already dead.",
        kind: "hard",
        deltas: { europeans: 8, saudis: -14, media: 8 },
        ...hindsight("You seized Lincoln in 1987. Cranston still had a hearing. The bill stayed a 1987 bill."),
      },
    ],
    sources: ["Keating Five 1987", "FSLIC insolvency 1987"],
    visibleFactions: ROOM,
    next: "rtc-1989",
  },
  {
    id: "rtc-1989",
    year: 1989,
    yearLabel: "1989",
    title: "The unwind that worked",
    titleUs: "FIRREA / RTC",
    titleIran: "Seizure",
    era: "sl",
    status: "playable",
    referee: {
      paragraphs: [
        "FIRREA. FSLIC dies. RTC is born. Slow. Public. Expensive. Some jail. Keating will do time. We will call this competence. The next book will hear that we can clean this up.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "europeans",
        audience: "us",
        rant: "Stand up the RTC. Sell the dirt. Do it in daylight. The fund is gone. Taxpayers own this.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "The desk is done. The book is a resolution. Jail is a real overlay this time.",
        face: "keating",
      },
    ],
    situationUs: "Bush sits. FIRREA is the bill. Stand up the RTC, or forbear again and let the bill become 2008 early.",
    situationIran: "They are coming with a resolution. The cubicle cannot save you. The warehouse was always empty.",
    iranChoices: [
      {
        id: "ir-seized",
        label: "Take the seizure",
        summary: "Lincoln dies.",
        kind: "walk",
        historical: true,
        deltas: { irgc: 8, leader: -15, street: -8 },
        flags: { s_l_worked: true, iran_face: "meriwether" },
      },
      {
        id: "ir-fight-rtc",
        label: "Fight the RTC in court",
        summary: "Delay the unwind.",
        kind: "hard",
        deltas: { leader: 4, europeans: -6, media: -8 },
        ...serve("The RTC still takes the keys", "You sued. They still sold the dirt. The unwind that worked, worked. You serve a delay. The rail continues on."),
      },
    ],
    usChoices: [
      {
        id: "us-rtc",
        label: "Stand up the RTC",
        summary: "Slow. Public. Some jail.",
        kind: "hard",
        historical: true,
        deltas: { europeans: 10, street: -6, saudis: -4, liberals: -40, future_irgc_grudge: 40 },
        flags: { s_l_worked: true },
      },
      {
        id: "us-forbear-89",
        label: "Forbear again",
        summary: "The bill becomes a novel.",
        kind: "soft",
        deltas: { europeans: -20, street: 4 },
        ending: "hoover",
        resultTitle: "You let the zombies compound",
        result:
          "Forbearance in 1989 is how 2008 arrives early. History did not take the complete wipe. AL. Time travel is the honest button.",
      },
    ],
    sources: ["FIRREA 1989", "Resolution Trust Corporation"],
    visibleFactions: ROOM,
    next: "rtc-1995",
  },
  {
    id: "rtc-1995",
    year: 1995,
    yearLabel: "1995",
    title: "We call it competence",
    titleUs: "The RTC closes",
    titleIran: "Leave the dirt",
    era: "sl",
    status: "playable",
    referee: {
      paragraphs: [
        "The RTC winds down. Taxpayers ate the hole. Keating did time. We will say a sector can be unwound. Greenwich is already building a fund that will treat this as a license.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "europeans",
        audience: "us",
        rant: "The bill is public. The dirt is sold. Close the shop and take the win. The next book is not our charter.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "The duration gap is a resolved case file. The next book is a model. Models do not need a warehouse.",
      },
      {
        faction: "cia",
        audience: "us",
        rant: "A sector died in daylight. Markets learned. Complexity is now a private problem.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "Lincoln is a museum. You can stay a resolution man or you can sit Greenwich. The cubicle prefers Greenwich.",
        face: "meriwether",
      },
    ],
    situationUs:
      "Bush is gone. Clinton sits. The RTC is finishing. Declare the S&L over, or keep a standing desk that hunts the next off-balance-sheet costume.",
    situationIran:
      "The dirt is sold. Keating is in a cell. You can stay with the residue or take the lesson to Greenwich. The lesson they want is: we can close a book.",
    iranChoices: [
      {
        id: "ir-leave-dirt",
        label: "Leave for Greenwich",
        summary: "The next book is a model.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -4, leader: 6, cia: 4 },
        flags: { iran_face: "meriwether" },
      },
      {
        id: "ir-stay-resolution",
        label: "Stay a resolution man",
        summary: "The dirt still has addresses.",
        kind: "walk",
        deltas: { irgc: 6, leader: -6 },
        ...hindsight("You stayed with the residue. Greenwich still built the model. You have the point."),
      },
    ],
    usChoices: [
      {
        id: "us-rtc-close",
        label: "Declare the S&L over",
        summary: "Competence. Close the shop.",
        kind: "deal",
        historical: true,
        deltas: { europeans: 6, media: 4, future_irgc_grudge: -8 },
      },
      {
        id: "us-keep-rtc",
        label: "Keep a standing resolution desk",
        summary: "The next costume is coming.",
        kind: "hard",
        deltas: { europeans: 4, saudis: -6, drone_holes_known: 8 },
        ...hindsight("You kept a desk that hunts vehicles. Greenwich still got a weekend. You have the point."),
      },
    ],
    sources: ["RTC sunset 1995", "Keating convictions"],
    visibleFactions: ROOM,
    next: "ltcm-1998",
  },
  {
    id: "ltcm-1998",
    year: 1998,
    yearLabel: "1998",
    title: "When genius failed",
    titleUs: "The room",
    titleIran: "The weekend",
    era: "ltcm",
    status: "playable",
    branchPoint: true,
    clocksOn: true,
    referee: {
      paragraphs: [
        "Long-Term Capital. Meriwether. Nobels. Convergence trades. Leverage. Russia defaulted in August. Fourteen banks in a room at the NY Fed in September. Bear says no. No Treasury check. We will call this private. We will call this a put anyway.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "Not a bailout. A consortium. If they fire-sale the book, every desk on the other side dies with them. Get them in a room.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "VaR said this could not happen. VaR is a cubicle. Russia happened. The counterparties have the guns.",
        face: "meriwether",
      },
    ],
    situationUs:
      "Clinton sits. Russia blew a hole in Greenwich. McDonough wants fourteen banks in a room. Bear will say no. Call it a recap, not a bailout.",
    situationIran:
      "You are Meriwether. The model is the letterhead. The room is about to own the book. Buffett sent a fax. Bear will not come.",
    iranChoices: [
      {
        id: "ir-take-room",
        label: "Take the consortium",
        summary: "The room recaps you.",
        kind: "deal",
        historical: true,
        deltas: { irgc: 8, leader: -8, cia: 6 },
        flags: { ltcm_worked: true },
      },
      {
        id: "ir-file",
        label: "File",
        summary: "Chapter 11. Fire sale.",
        kind: "walk",
        deltas: { irgc: -20, leader: -20 },
        ...adapts(
          "The fire sale",
          "You filed. Every desk on the other side marked you overnight. The room still happens, uglier, without you as letterhead. The rail continues on. AL on the ugliness, not on the hole.",
        ),
      },
    ],
    usChoices: [
      {
        id: "us-room",
        label: "Get them in a room",
        summary: "Not a bailout.",
        kind: "deal",
        historical: true,
        deltas: { cia: 8, media: -4, street: 2, irgc: 6 },
        flags: { ltcm_worked: true },
      },
      {
        id: "us-call-put",
        label: "Call it a put, out loud",
        summary: "And still run the room.",
        kind: "hard",
        deltas: { media: 8, cia: -4, street: -4 },
        flags: { ltcm_worked: true },
        ...hindsight("You ran the room and you named the put. Greenwich still got saved. The next book heard you anyway."),
      },
    ],
    sources: ["Lowenstein, When Genius Failed", "NY Fed LTCM meeting 23 Sep 1998", "Russia default 17 Aug 1998"],
    visibleFactions: ROOM,
    next: "glba-1999",
  },
  {
    id: "glba-1999",
    year: 1999,
    yearLabel: "1999",
    title: "Because 1998 worked",
    titleUs: "GLBA",
    titleIran: "The wall comes down",
    era: "ltcm",
    status: "playable",
    referee: {
      paragraphs: [
        "Gramm-Leach-Bliley. The wall between commercial and investment banks comes down. The sentence is: 1998 worked. We can handle complexity.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "irgc",
        audience: "us",
        rant: "The room proved the system can close a book. Let the books get bigger.",
      },
      {
        faction: "cia",
        audience: "iran",
        rant: "You lived. The put is now a story. Use it.",
      },
    ],
    situationUs: "The 1998 weekend is already a success story. Repeal Glass-Steagall. The models worked.",
    situationIran: "The wall is coming down. You can be everything. The cubicle will call that synergy.",
    iranChoices: [
      {
        id: "ir-glba-yes",
        label: "Be everything",
        summary: "Commercial plus investment.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -4, leader: 6, china: 4 },
      },
      {
        id: "ir-glba-no",
        label: "Stay a fund",
        summary: "Do not become the country.",
        kind: "walk",
        deltas: { irgc: 4, leader: -4 },
        ...hindsight("You stayed a fund. The country still became a CDO."),
      },
    ],
    usChoices: [
      {
        id: "us-glba",
        label: "Repeal the wall",
        summary: "GLBA.",
        kind: "deal",
        historical: true,
        deltas: { irgc: -4, saudis: 6, cia: 4 },
      },
      {
        id: "us-keep-wall",
        label: "Keep Glass-Steagall",
        summary: "1998 is not a license.",
        kind: "hard",
        deltas: { saudis: -8, irgc: 4 },
        ...hindsight("The wall stayed. The houses still wanted to be AAA. The book found another costume."),
      },
    ],
    sources: ["Gramm-Leach-Bliley Act 1999"],
    visibleFactions: ROOM,
    next: "levitt-2000",
  },
  {
    id: "levitt-2000",
    year: 2000,
    yearLabel: "2000",
    title: "The auditor is the consultant",
    titleUs: "Levitt vs Lay",
    titleIran: "Write the SEC",
    era: "enron",
    status: "playable",
    electionYear: true,
    referee: {
      paragraphs: [
        "Arthur Levitt wants auditor independence. Lay writes the SEC. Andersen is Enron's auditor and its consultant. The cubicle is auditing the cubicle. Enron will pass every audit.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "venezuela",
        audience: "us",
        rant: "Independence is expensive. Enron finds the current setup cheaper. That is a quote. Lay signed it.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "Write Levitt. The consultant is how you keep the auditor friendly. The warehouse can wait.",
        face: "lay",
      },
    ],
    situationUs: "Levitt wants to split audit from consulting. Lay's letter is on the desk. Houston is a friend of the building.",
    situationIran: "You are Lay. Andersen signs the books and sells you the advice. Write the SEC. The SPEs need the cubicle to stay friendly.",
    iranChoices: [
      {
        id: "ir-write-levitt",
        label: "Write the SEC",
        summary: "Kill independence.",
        kind: "covert",
        historical: true,
        deltas: { venezuela: 8, drone_holes_known: -6, leader: 4 },
        flags: { iran_face: "lay" },
      },
      {
        id: "ir-split-andersen",
        label: "Split the auditor",
        summary: "Let them only sign.",
        kind: "hard",
        deltas: { venezuela: -8, drone_holes_known: 10, leader: -6 },
        ...hindsight("Andersen only signed. Someone still had to drive to the SPE. You did not. You have the point anyway."),
      },
    ],
    usChoices: [
      {
        id: "us-water-levitt",
        label: "Water Levitt down",
        summary: "Independence can wait.",
        kind: "soft",
        historical: true,
        deltas: { venezuela: 6, drone_holes_known: -4, media: -2 },
      },
      {
        id: "us-back-levitt",
        label: "Back Levitt",
        summary: "Auditor cannot be consultant.",
        kind: "hard",
        deltas: { venezuela: -10, drone_holes_known: 12, saudis: -6 },
        ...hindsight("You backed Levitt. Enron still had SPEs. Someone still had to drive to the address. You have the point."),
      },
    ],
    sources: ["Lay letter to Levitt on auditor independence", "Arthur Andersen dual role"],
    visibleFactions: ROOM,
    next: "enron-2001",
  },
  {
    id: "enron-2001",
    year: 2001,
    yearLabel: "2001",
    title: "The audit passed",
    titleUs: "Drive to the SPE",
    titleIran: "Raptor",
    era: "enron",
    status: "playable",
    branchPoint: true,
    referee: {
      paragraphs: [
        "October restatement. Shredders. December 2 bankruptcy. Mark-to-market on contracts with no market. Chewco, LJM, Raptors. Fastow has the guns. The audit passed. Every year. To catch this you leave the cubicle and drive to the vehicle.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "irgc",
        audience: "iran",
        rant: "The Raptors unwind if the stock drops. The stock is dropping. The warehouse is a Cayman address. Andersen is still signing.",
        face: "lay",
      },
      {
        faction: "cia",
        audience: "us",
        rant: "Houston. A campaign. An energy book. The filing is clean until it is not. Nobody has driven to the SPE.",
      },
    ],
    situationUs:
      "Bush sits. Enron is restating. The audit passed. The invoices have addresses in the Caymans. The 401k is main street.",
    situationIran:
      "You are Lay. Fastow built the vehicles. Andersen signed. The cubicle is not going to save the stock. You can still mark it, or you can shred.",
    actionPrompt: "Leave the cubicle?",
    iranChoices: [
      {
        id: "ir-hide-spe",
        label: "Keep the SPEs off the book",
        summary: "The audit passed.",
        kind: "soft",
        historical: true,
        deltas: { irgc: -12, drone_holes_known: -8, street: -10, leader: -6 },
      },
      {
        id: "ir-drive-spe",
        label: "Drive to the SPE",
        summary: "Mark it. Name Fastow.",
        kind: "hard",
        deltas: { irgc: 8, drone_holes_known: 30, leader: -10, street: -4 },
        ...drive("the Cayman address on the Raptor invoice"),
      },
    ],
    usChoices: [
      {
        id: "us-watch-enron",
        label: "Watch the bankruptcy",
        summary: "The filing will handle it.",
        kind: "ignore",
        historical: true,
        deltas: { street: -8, media: 8, venezuela: -6 },
      },
      {
        id: "us-drive-enron",
        label: "Send someone to the SPE",
        summary: "Leave the cubicle.",
        kind: "covert",
        deltas: { drone_holes_known: 30, street: 4, media: 10, venezuela: -10 },
        ...drive("the SPE"),
      },
    ],
    sources: ["Enron bankruptcy 2 Dec 2001", "SPE restatement Oct 2001", "Andersen shredding"],
    visibleFactions: ROOM,
    next: "sox-2002",
  },
  {
    id: "sox-2002",
    year: 2002,
    yearLabel: "2002",
    title: "The CEO signs",
    titleUs: "SOX",
    titleIran: "Andersen is gone",
    era: "enron",
    status: "playable",
    referee: {
      paragraphs: [
        "Sarbanes-Oxley. The CEO signs the books. Andersen dies as a going concern. WorldCom is a sentence on this card, not a movie. We fixed accounting. The next book will hide in a SIV anyway.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "saudis",
        audience: "us",
        rant: "Pass it 99-0. Sign it. Call it done. The houses are not Enron.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "Andersen is dead. You will sign the next book yourself. The cubicle just got a law. The warehouse did not.",
        face: "lay",
      },
    ],
    situationUs: "Pass SOX. WorldCom is the rhyme in the same year. Call it done, or keep hunting the next off-balance-sheet vehicle.",
    situationIran: "The auditor who signed you is dead. Skilling is going to jail. The houses are already being packed as AAA.",
    iranChoices: [
      {
        id: "ir-sign-sox",
        label: "Sign the next book",
        summary: "The law is a ritual.",
        kind: "deal",
        historical: true,
        deltas: { drone_holes_known: 4, leader: -4 },
        flags: { sox_worked: true, iran_face: "mozilo" },
      },
      {
        id: "ir-refuse-sign",
        label: "Refuse to sign a book you have not driven",
        summary: "Leave.",
        kind: "walk",
        deltas: { leader: -20, drone_holes_known: 10 },
        ...moral("You would not sign a book you had not driven to. A replacement signed. The Street continues."),
      },
    ],
    usChoices: [
      {
        id: "us-sox-done",
        label: "Pass SOX and call it done",
        summary: "Accounting is fixed.",
        kind: "deal",
        historical: true,
        deltas: { media: 6, saudis: 8, drone_holes_known: 6 },
        flags: { sox_worked: true },
      },
      {
        id: "us-sox-hunt",
        label: "Pass SOX and hunt SIVs",
        summary: "The next SPE has a new name.",
        kind: "hard",
        deltas: { drone_holes_known: 16, saudis: -6, irgc: 4 },
        flags: { sox_worked: true },
        ...hindsight("You passed the law and you kept hunting. The houses still wanted to be AAA. You have the point."),
      },
    ],
    sources: ["Sarbanes-Oxley Act 30 Jul 2002", "WorldCom 2002"],
    visibleFactions: ROOM,
    next: "dream-2003",
  },
  {
    id: "dream-2003",
    year: 2003,
    yearLabel: "2003",
    title: "The American Dream",
    titleUs: "Ownership society",
    titleIran: "A 30-year note as a product",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "The S&L housing sermon, louder. GSEs. Subprime as inclusion. Countrywide. The cubicle will rate a stack of 620 FICOs as AAA. SOX does not unwind a mortgage.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "street",
        audience: "us",
        rant: "Everyone deserves a house. The last unwind worked. The audit of the originator will pass.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "Originate. Sell. The SPE is now a trust. The rating is the product. Do not drive to the house.",
        face: "mozilo",
      },
    ],
    situationUs: "Ownership society. Push the GSEs. The houses are not Enron. That is the sentence.",
    situationIran: "You are Mozilo. A 30-year note is a product you sell, not a loan you keep. The address is a family. The cubicle will not visit.",
    iranChoices: [
      {
        id: "ir-originate-sell",
        label: "Originate and sell",
        summary: "The house leaves your book.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -8, oil_pain: 10, venezuela: 8, street: 6, china: 6 },
        flags: { iran_face: "mozilo" },
      },
      {
        id: "ir-drive-house",
        label: "Drive to the house",
        summary: "See if anyone lives there.",
        kind: "hard",
        deltas: { irgc: 6, oil_pain: -6, drone_holes_known: 12, leader: -4 },
        ...drive("the house on the note"),
      },
    ],
    usChoices: [
      {
        id: "us-ownership",
        label: "Push ownership",
        summary: "GSEs, subprime as inclusion.",
        kind: "deal",
        historical: true,
        deltas: { street: 6, oil_pain: 8, china: 6, my_party: 4 },
      },
      {
        id: "us-underwrite",
        label: "Make them keep the note",
        summary: "No originate-to-sell.",
        kind: "hard",
        deltas: { street: -8, oil_pain: -8, saudis: -8 },
        ...hindsight("Originators kept the risk. The AAA factory slowed. The country still wanted the dream. You have the point."),
      },
    ],
    sources: ["American Dream Downpayment Act 2003", "GSE affordable housing goals"],
    visibleFactions: ROOM,
    next: "sec-2004",
  },
  {
    id: "sec-2004",
    year: 2004,
    yearLabel: "2004",
    title: "Forty to one",
    titleUs: "The CSE",
    titleIran: "Internal models",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "SEC Consolidated Supervised Entity. The five investment banks may compute their own net capital. Twelve to one becomes forty to one. The cubicle writes the rule for the cubicle. Bear, Lehman, Merrill, Goldman, Morgan Stanley.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "venezuela",
        audience: "us",
        rant: "The models are sophisticated. Europe is already there. If you keep 12 to 1 they will book the trades in London.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "Leverage is a product. The CSE is permission to sell more of it. Do not drive to the houses that will sit under the AAA.",
        face: "mozilo",
      },
      {
        faction: "cia",
        audience: "us",
        rant: "Holding companies at the Fed. Broker-dealers at the SEC. The gap is the book. Fill it with a model.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "The old haircut is for commercial banks. You are a market. Markets mark themselves.",
        face: "mozilo",
      },
    ],
    situationUs:
      "The five want the CSE. Internal models. 40 to 1. SOX just made CEOs sign. This rule lets the signed book get bigger.",
    situationIran:
      "You are the Street after Houston. The haircut is about to die. The houses are already a factory. Forty times is a costume SOX does not see.",
    iranChoices: [
      {
        id: "ir-cse-yes",
        label: "Lever the book",
        summary: "Forty to one.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -8, leader: 8, venezuela: 6 },
        flags: { iran_face: "mozilo" },
      },
      {
        id: "ir-cse-no",
        label: "Stay at twelve to one",
        summary: "The haircut is the job.",
        kind: "walk",
        deltas: { irgc: 8, leader: -8 },
        ...hindsight("You kept the haircut. The other four did not. You have the point."),
      },
    ],
    usChoices: [
      {
        id: "us-cse",
        label: "Grant the CSE",
        summary: "Internal models. 40 to 1.",
        kind: "deal",
        historical: true,
        deltas: { venezuela: 8, irgc: -6, cia: 4, drone_holes_known: -6 },
      },
      {
        id: "us-keep-12",
        label: "Keep twelve to one",
        summary: "The haircut stays.",
        kind: "hard",
        deltas: { venezuela: -10, saudis: -6, irgc: 6, drone_holes_known: 8 },
        ...hindsight("The haircut stayed. The houses still wanted to be AAA. You have the point."),
      },
    ],
    sources: ["SEC CSE program 2004", "Net capital exemption"],
    visibleFactions: ROOM,
    next: "jackson-2005",
  },
  {
    id: "jackson-2005",
    year: 2005,
    yearLabel: "2005",
    title: "Jackson Hole",
    titleUs: "Rajan speaks",
    titleIran: "The model is the territory",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "Rajan at Jackson Hole. The system is holding more risk, not less. The room mostly does not want to hear it. 1998 worked. SOX worked. The houses are not a SPE.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "A staff economist is nervous. The models are fine. 1998 was contained. This will be too.",
      },
      {
        faction: "venezuela",
        audience: "iran",
        rant: "AAA. We ran the numbers in the cubicle. We did not drive to Las Vegas.",
      },
    ],
    situationUs: "Jackson Hole. Rajan says the system is more fragile. The room wants to celebrate the Great Moderation.",
    situationIran: "A Fed conference just described your book as a weapon. Keep originating. The rating is still AAA.",
    iranChoices: [
      {
        id: "ir-ignore-rajan",
        label: "Keep the factory on",
        summary: "AAA is the product.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -6, oil_pain: 8, venezuela: 4 },
      },
      {
        id: "ir-listen-rajan",
        label: "Mark the pipeline",
        summary: "Slow the originations.",
        kind: "soft",
        deltas: { irgc: 6, oil_pain: -8, leader: -6 },
        ...hindsight("You listened at Jackson Hole. The factory next door did not. You have the point."),
      },
    ],
    usChoices: [
      {
        id: "us-moderation",
        label: "Celebrate the Great Moderation",
        summary: "Rajan is a scold.",
        kind: "ignore",
        historical: true,
        deltas: { cia: 4, oil_pain: 4, media: 2 },
      },
      {
        id: "us-listen-rajan",
        label: "Listen to Rajan",
        summary: "The system is holding more risk.",
        kind: "hard",
        deltas: { cia: -4, oil_pain: -6, media: 4 },
        ...hindsight("You listened. The houses were still a factory. You have the point."),
      },
    ],
    sources: ["Raghuram Rajan Jackson Hole 2005"],
    visibleFactions: ROOM,
    next: "peak-2006",
  },
  {
    id: "peak-2006",
    year: 2006,
    yearLabel: "2006",
    title: "The address is empty",
    titleUs: "Housing peaks",
    titleIran: "Friends of Angelo",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "Case-Shiller peaks. New Century is already coughing. Countrywide is still a factory. The cubicle still prints AAA on a stack of 620s. Nobody has driven to Las Vegas.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "street",
        audience: "us",
        rant: "Prices are a national good. A cooling is healthy. Do not call it a hole.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "The warehouse is a subdivision. Drive at noon and the garage is empty. The rating does not care.",
        face: "mozilo",
      },
      {
        faction: "venezuela",
        audience: "us",
        rant: "The structure is investment grade. We ran the numbers. We did not walk the cul-de-sac.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "Originate. Sell. The peak is a rumor until the commercial paper stops. Keep the factory on.",
        face: "mozilo",
      },
    ],
    situationUs:
      "Housing has stopped going up. The Street says a plateau. The invoices still have addresses. Someone could still drive.",
    situationIran:
      "You are Mozilo. Friends of Angelo got the good rate. The house on the tape may not have a family. The cubicle will not visit.",
    actionPrompt: "Leave the cubicle?",
    iranChoices: [
      {
        id: "ir-keep-factory",
        label: "Keep the factory on",
        summary: "AAA is still the product.",
        kind: "hard",
        historical: true,
        deltas: { irgc: -8, oil_pain: 10, venezuela: 4, street: -4 },
      },
      {
        id: "ir-drive-vegas",
        label: "Drive to Las Vegas",
        summary: "See who lives there.",
        kind: "hard",
        deltas: { irgc: 8, oil_pain: -8, drone_holes_known: 16, leader: -6 },
        ...drive("a cul-de-sac of empty houses with AAA on the tape"),
      },
    ],
    usChoices: [
      {
        id: "us-peak-ok",
        label: "Call it a plateau",
        summary: "Markets cool.",
        kind: "ignore",
        historical: true,
        deltas: { oil_pain: 6, media: 2, drone_holes_known: -4 },
      },
      {
        id: "us-drive-peak",
        label: "Send someone to the houses",
        summary: "Leave the cubicle.",
        kind: "covert",
        deltas: { drone_holes_known: 16, oil_pain: -6, media: 6 },
        ...drive("Las Vegas in 2006"),
      },
    ],
    sources: ["Case-Shiller peak 2006", "New Century 2006-2007", "Friends of Angelo"],
    visibleFactions: ROOM,
    next: "contained-2007",
  },
  {
    id: "contained-2007",
    year: 2007,
    yearLabel: "2007",
    title: "Subprime is contained",
    titleUs: "Contained",
    titleIran: "The factory seizes",
    era: "housing",
    status: "playable",
    branchPoint: true,
    clocksOn: true,
    referee: {
      paragraphs: [
        "August 2007. The 1998 sentence, said again. Subprime is contained. The SIVs are SPEs in a new costume. SOX does not unwind them. Nobody drove to the houses.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "Contained. The models say the rest of the book is fine. 1998 was a weekend. This is a sector.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "The commercial paper is not rolling. The warehouse is a trust in the Caymans again. Drive and you will not like the address.",
        face: "mozilo",
      },
    ],
    situationUs: "Bernanke and Paulson. Contained is the word. The TED is moving. The houses are a sector, you tell yourselves.",
    situationIran: "Countrywide is the weather. The AAA is melting. You can still mark it, or you can say contained along with them.",
    iranChoices: [
      {
        id: "ir-contained",
        label: "It is contained",
        summary: "Keep the factory language.",
        kind: "soft",
        historical: true,
        deltas: { irgc: -10, oil_pain: 10, venezuela: -6, street: -6 },
        flags: { iran_face: "cayne" },
      },
      {
        id: "ir-mark-2007",
        label: "Mark the housing book",
        summary: "Drive to the houses.",
        kind: "hard",
        deltas: { irgc: 8, oil_pain: -8, drone_holes_known: 16, leader: -8 },
        ...drive("a street of empty houses with AAA on the tape"),
      },
    ],
    usChoices: [
      {
        id: "us-contained",
        label: "Say contained",
        summary: "1998 language.",
        kind: "ignore",
        historical: true,
        deltas: { media: 4, oil_pain: 8, cia: 4, street: -4 },
      },
      {
        id: "us-not-contained",
        label: "Say it is not contained",
        summary: "Name the book.",
        kind: "hard",
        deltas: { media: -6, oil_pain: -4, street: -8, cia: -4 },
        ...hindsight("You refused the 1998 sentence. The book was the country. You have the point. The book continues on."),
      },
    ],
    sources: ["Bernanke 2007 subprime contained", "August 2007 commercial paper freeze"],
    visibleFactions: ROOM,
    next: "bear-2008",
  },
  {
    id: "bear-2008",
    year: 2008,
    yearLabel: "Mar 2008",
    title: "The bank that said no",
    titleUs: "Bear",
    titleIran: "You are Bear",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "Bear Stearns. The bank that would not recap LTCM. JPMorgan, the window, a weekend. The rhyme is the point.",
      ],
      tags: ["LT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "Do Bear. Show that a weekend still works. Lehman is watching.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "In 1998 we said no to the room. The room has a long memory.",
        face: "cayne",
      },
    ],
    situationUs: "Bear is dying on a Friday. JPMorgan wants a backstop. 1998 says a weekend works.",
    situationIran: "You are Cayne. In 1998 you would not recap Greenwich. The window is now the only buyer.",
    iranChoices: [
      {
        id: "ir-bear-sold",
        label: "Sell to JPMorgan",
        summary: "A weekend price.",
        kind: "deal",
        historical: true,
        deltas: { irgc: 4, leader: -12, street: -4 },
        flags: { iran_face: "fuld" },
      },
      {
        id: "ir-bear-file",
        label: "File",
        summary: "No weekend.",
        kind: "walk",
        deltas: { irgc: -16, leader: -16 },
        ...adapts("Monday", "You filed. The rest of the street marked you at zero before the open. The rail still has Lehman. AL on the hours, not on the hole."),
      },
    ],
    usChoices: [
      {
        id: "us-bear-backstop",
        label: "Backstop JPMorgan",
        summary: "A weekend. Again.",
        kind: "deal",
        historical: true,
        deltas: { cia: 6, media: -4, street: 2, irgc: 4 },
      },
      {
        id: "us-bear-no",
        label: "Let Bear file",
        summary: "No more rooms.",
        kind: "hard",
        deltas: { cia: -8, media: 6, irgc: -12, street: -10 },
        ...adapts("The rest of the street", "You let Bear go. The TED does the rest. Lehman is next week, not next year. The rail continues on, uglier."),
      },
    ],
    sources: ["Bear Stearns sale to JPMorgan March 2008"],
    visibleFactions: ROOM,
    next: "lehman-2008",
  },
  {
    id: "lehman-2008",
    year: 2008,
    yearLabel: "Sep 2008",
    title: "The book will not close",
    titleUs: "Lehman",
    titleIran: "You are Fuld",
    era: "housing",
    status: "playable",
    branchPoint: true,
    referee: {
      paragraphs: [
        "Lehman. Barclays wants a clean name. Washington will not do Bear twice in public. The book is counterparties all the way down. This is the unwind that will not close.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "No more Bear. Moral hazard. The rest of the book is not Lehman. Contained, again, as a wish.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "There is no warehouse to drive to that closes this. The invoice is every desk. That is the theme.",
        face: "fuld",
      },
    ],
    situationUs: "Sunday. Barclays. No American backstop. Let Lehman file, or do Bear again and own it.",
    situationIran: "You are Fuld. The room is not coming. 1998 was a put for Greenwich. Houston went to jail. You are the country now.",
    iranChoices: [
      {
        id: "ir-lehman-file",
        label: "File",
        summary: "Chapter 11.",
        kind: "walk",
        historical: true,
        deltas: { irgc: -18, leader: -18, street: -12, oil_pain: 16 },
        flags: { iran_face: "blankfein" },
      },
      {
        id: "ir-lehman-beg",
        label: "Beg for Bear's weekend",
        summary: "The window.",
        kind: "soft",
        deltas: { leader: -8, cia: 4 },
        ...serve("No weekend", "You begged. They had done Bear. They would not do you. You file anyway. You serve a hope. The rail continues on."),
      },
    ],
    usChoices: [
      {
        id: "us-lehman-file",
        label: "Let Lehman file",
        summary: "Moral hazard.",
        kind: "hard",
        historical: true,
        deltas: { cia: -4, media: 6, street: -14, oil_pain: 16, irgc: -10 },
      },
      {
        id: "us-lehman-save",
        label: "Do Bear again",
        summary: "Backstop a buyer.",
        kind: "deal",
        deltas: { cia: 4, media: -10, street: 4, saudis: -8 },
        artisticLicense: "lehman-save",
        ...adapts(
          "AIG is still Monday",
          "You saved Lehman. AIG FP is still the other book. The unwind still will not close. AL on Lehman living. Not on the hole. The rail continues on.",
        ),
      },
    ],
    artisticLicense: [
      {
        id: "lehman-save",
        title: "Saving Lehman",
        body: "History let Lehman file. This button keeps the name alive for a week. AIG is still the next card. Labelled AL.",
      },
    ],
    sources: ["Lehman bankruptcy 15 Sep 2008"],
    visibleFactions: ROOM,
    next: "aig-2008",
  },
  {
    id: "aig-2008",
    year: 2008,
    yearLabel: "Sep 2008",
    title: "The insurance was the book",
    titleUs: "AIG FP",
    titleIran: "The CDS",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "AIG Financial Products. CDS on the AAA. The insurance was the leverage. SOX does not unwind a derivative. The window takes 79.9 percent.",
      ],
      tags: ["LT"],
    },
    briefings: [
      {
        faction: "irgc",
        audience: "us",
        rant: "If AIG FP fails, every desk that bought the insurance is naked. This is LTCM with a country attached.",
      },
      {
        faction: "cia",
        audience: "iran",
        rant: "We cannot do Lehman twice in two days. The window is the buyer.",
      },
    ],
    situationUs: "AIG FP. The insurance on the AAA. Take 79.9 percent or watch the counterparties go.",
    situationIran: "You sold protection on a stack of houses. The houses are the invoice. Nobody drove there. The window is here.",
    iranChoices: [
      {
        id: "ir-aig-window",
        label: "Take the window",
        summary: "79.9 percent.",
        kind: "deal",
        historical: true,
        deltas: { irgc: 6, leader: -10, cia: 8 },
        flags: { iran_face: "blankfein" },
      },
      {
        id: "ir-aig-file",
        label: "File",
        summary: "No window.",
        kind: "walk",
        deltas: { irgc: -22, street: -18 },
        ending: "seizure",
      },
    ],
    usChoices: [
      {
        id: "us-aig-take",
        label: "Take 79.9 percent",
        summary: "The window.",
        kind: "hard",
        historical: true,
        deltas: { cia: 10, media: -8, street: -6, saudis: -6 },
      },
      {
        id: "us-aig-no",
        label: "Let AIG file",
        summary: "Lehman twice.",
        kind: "soft",
        deltas: { street: -20, irgc: -16, media: 4 },
        ending: "hoover",
        resultTitle: "The insurance was the country",
        result:
          "AIG FP was the counterparties. You let it file. History did not take this as a complete map. AL. Time travel is the honest button.",
      },
    ],
    sources: ["AIG rescue 16 Sep 2008"],
    visibleFactions: ROOM,
    next: "tarp-fail-2008",
  },
  {
    id: "tarp-fail-2008",
    year: 2008,
    yearLabel: "Sep 2008",
    title: "The House says no",
    titleUs: "TARP fails",
    titleIran: "The put is a vote",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "TARP, first vote. The House says no. The book is now a roll call. Main street watches the ticker.",
      ],
      tags: ["LT"],
    },
    briefings: [
      {
        faction: "saudis",
        audience: "us",
        rant: "My caucus will not vote a bailout. They drove to their districts. The districts have empty houses.",
      },
      {
        faction: "street",
        audience: "iran",
        rant: "They will vote again. They always vote again. The put is not dead. It is late.",
      },
    ],
    situationUs: "The first TARP vote. Your caucus hates it. The ticker will punish a no. History is a no, then a yes.",
    situationIran: "Washington just voted the put down. The book does not care about the civics. It cares about Monday.",
    iranChoices: [
      {
        id: "ir-wait-tarp",
        label: "Wait for the second vote",
        summary: "The put is late, not dead.",
        kind: "soft",
        historical: true,
        deltas: { irgc: -6, street: -6, media: 4 },
      },
      {
        id: "ir-raise-capital",
        label: "Raise capital without them",
        summary: "Do not wait for the put.",
        kind: "hard",
        deltas: { irgc: 4, leader: -8 },
        ...hindsight("You raised without TARP. The rest of the street waited. You have the point."),
      },
    ],
    usChoices: [
      {
        id: "us-tarp-no",
        label: "Vote no",
        summary: "The first roll call.",
        kind: "hard",
        historical: true,
        deltas: { saudis: 6, my_party: 4, street: -8, media: 8, oil_pain: 8 },
      },
      {
        id: "us-tarp-yes-1",
        label: "Whip it through the first time",
        summary: "Do not wait for the crash to teach them.",
        kind: "deal",
        deltas: { saudis: -10, my_party: -8, street: 4 },
        ...hindsight("You whipped TARP through the first time. The ticker still hated you. You have the point."),
      },
    ],
    sources: ["TARP first House vote 29 Sep 2008"],
    visibleFactions: ROOM,
    next: "campaign-2008",
  },
  {
    id: "campaign-2008",
    year: 2008,
    yearLabel: "Sep 2008",
    title: "Country or ambition",
    titleUs: "The campaigns",
    titleIran: "The election is a ticker",
    era: "housing",
    status: "playable",
    electionYear: true,
    referee: {
      paragraphs: [
        "McCain suspends and goes to Washington. Obama looks at the polls and keeps campaigning. Presidents have to deal with more than one thing. That is the sentence. Country over ambition is the offramp.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "media",
        audience: "us",
        rant: "McCain looks serious. Obama looks like a president who can walk and chew. The polls like the chew.",
      },
      {
        faction: "street",
        audience: "iran",
        rant: "They will campaign. The book does not vote.",
      },
    ],
    situationUs:
      "You are still Bush. The nominees are the country's other desk this week. McCain wants to suspend. Obama wants to keep campaigning. Historical for the winner is keep campaigning.",
    situationIran: "Washington is having a civics play. Your book is still open. TARP is still a second vote.",
    iranChoices: [
      {
        id: "ir-ignore-campaign",
        label: "Ignore the campaigns",
        summary: "The book is the job.",
        kind: "ignore",
        historical: true,
        deltas: { media: 2 },
      },
      {
        id: "ir-pause-deal",
        label: "Pause the book for the vote",
        summary: "Let them pass TARP.",
        kind: "soft",
        deltas: { leader: -4, cia: 2 },
        ...hindsight("You paused origination while they voted. The rest of the street did not. You have the point."),
      },
    ],
    usChoices: [
      {
        id: "us-keep-campaign",
        label: "Keep campaigning",
        summary: "Presidents juggle.",
        kind: "hard",
        historical: true,
        deltas: { media: 6, my_party: 4, opposing_party: -2 },
      },
      {
        id: "us-suspend",
        label: "Suspend and go to Washington",
        summary: "Country over ambition.",
        kind: "deal",
        deltas: { media: -4, street: 4, saudis: 4 },
        ...hindsight(
          "You suspended. McCain's move. Country over ambition. Obama still sits in January. TARP still happens. You have the point.",
        ),
      },
    ],
    sources: ["McCain suspends campaign Sep 2008", "Obama keeps campaigning"],
    visibleFactions: ROOM,
    next: "tarp-pass-2008",
  },
  {
    id: "tarp-pass-2008",
    year: 2008,
    yearLabel: "Oct 2008",
    title: "The pause",
    titleUs: "TARP passes",
    titleIran: "The window is the desk",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "TARP passes. Capital injections. The window has the guns. This is not an unwind. It is a pause. SOX did not do this. The RTC was an unwind. This is a hold.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "Force the capital into the big nine. Do not ask. The RTC took years. We have days.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "You will take the money. You will say you did not need it. The window has the guns.",
        face: "blankfein",
      },
    ],
    situationUs: "Second vote. Pass it. Inject capital. Do not pretend this is the RTC.",
    situationIran: "They will make you take the money. The letterhead stays. The guns moved.",
    iranChoices: [
      {
        id: "ir-take-tarp",
        label: "Take the capital",
        summary: "The window.",
        kind: "deal",
        historical: true,
        deltas: { irgc: 10, leader: -4, cia: 6, street: -4 },
        flags: { iran_face: "blankfein" },
      },
      {
        id: "ir-refuse-tarp",
        label: "Refuse the capital",
        summary: "Pride.",
        kind: "hard",
        deltas: { leader: 4, irgc: -8 },
        ...serve("You take it anyway", "They force the capital. You serve the window. The rail continues on."),
      },
    ],
    usChoices: [
      {
        id: "us-tarp-pass",
        label: "Pass TARP and inject",
        summary: "A pause, not an unwind.",
        kind: "hard",
        historical: true,
        deltas: { cia: 8, saudis: -4, street: -6, media: -4, oil_pain: -6 },
      },
      {
        id: "us-rtc-again",
        label: "Stand up an RTC for the houses",
        summary: "Unwind, do not pause.",
        kind: "deal",
        deltas: { europeans: 10, street: -10, saudis: -12, future_irgc_grudge: 20 },
        ...hindsight("You tried to unwind the houses in daylight, like 1989. Congress hated it. You have the point. TARP still happens."),
      },
    ],
    sources: ["TARP signed 3 Oct 2008", "Capital Purchase Program"],
    visibleFactions: ROOM,
    next: "obama-2009",
  },
  {
    id: "obama-2009",
    year: 2009,
    yearLabel: "2009",
    title: "Stress tests",
    titleUs: "You sit",
    titleIran: "The window stays",
    era: "housing",
    status: "playable",
    electionYear: true,
    referee: {
      paragraphs: [
        "Obama sits. Stress tests. The cubicle, again, with a new name. Some capital. Not much jail. The houses are still the book.",
      ],
      tags: ["LT"],
    },
    briefings: [
      {
        faction: "cia",
        audience: "us",
        rant: "Publish the stress tests. Make the cubicle a show of force. Do not drive to every house.",
      },
      {
        faction: "irgc",
        audience: "iran",
        rant: "You passed. Of course you passed. Accountants wrote the exam for accountants.",
      },
    ],
    situationUs: "You sit. Stress tests. Geithner. The country wants hangings and got a spreadsheet.",
    situationIran: "The exam is a cubicle. You will pass. Main street wanted the warehouse.",
    iranChoices: [
      {
        id: "ir-pass-stress",
        label: "Pass the stress test",
        summary: "The cubicle exam.",
        kind: "deal",
        historical: true,
        deltas: { irgc: 6, street: -4, venezuela: 4 },
      },
      {
        id: "ir-show-houses",
        label: "Show them the houses",
        summary: "Drive.",
        kind: "hard",
        deltas: { drone_holes_known: 10, street: 4, leader: -6 },
        ...drive("the REO list"),
      },
    ],
    usChoices: [
      {
        id: "us-stress",
        label: "Publish the stress tests",
        summary: "A cubicle, in daylight.",
        kind: "deal",
        historical: true,
        deltas: { cia: 6, media: 4, street: -2 },
      },
      {
        id: "us-drive-reo",
        label: "Make them drive the REO",
        summary: "The address on the note.",
        kind: "hard",
        deltas: { drone_holes_known: 12, street: 4, irgc: 4 },
        ...drive("the foreclosure list"),
      },
    ],
    sources: ["SCAP stress tests 2009"],
    visibleFactions: ROOM,
    next: "jail-2011",
  },
  {
    id: "jail-2011",
    year: 2011,
    yearLabel: "2011",
    title: "Nobody went to jail",
    titleUs: "The empty dock",
    titleIran: "The cup",
    era: "housing",
    status: "playable",
    referee: {
      paragraphs: [
        "Keating went to jail. Skilling went to jail. 2011: the housing book did not. The cubicle prosecuted nobody who designed the factory. The RTC was an unwind. TARP was a pause. The pause held. Main street still has the houses.",
      ],
      tags: ["LT", "IT"],
    },
    briefings: [
      {
        faction: "street",
        audience: "us",
        rant: "Keating did time. This book was the country. You cannot jail a country. That is the sentence. It is also an excuse.",
      },
      {
        faction: "leader",
        audience: "iran",
        rant: "You are still the desk. The window saved the letterhead. The warehouse was always empty.",
        face: "blankfein",
      },
    ],
    situationUs:
      "The cup. File upstairs, or hold the rail. Historical is hold. Keating and Skilling were people. This was a system. That is Irish true and a dodge.",
    situationIran: "You are still sitting. The 401k is not. The audit passed until it could not. Nobody is coming for the desk.",
    iranChoices: [
      {
        id: "ir-hold-2011",
        label: "Hold the desk",
        summary: "The Street continues.",
        kind: "soft",
        historical: true,
        deltas: { leader: 4, street: -6 },
      },
      {
        id: "ir-walk-2011",
        label: "Walk",
        summary: "Leave the letterhead.",
        kind: "walk",
        deltas: { leader: -20, street: 4 },
        ...moral("You walked. The desk stayed. It is a moral victory. The machinery grinds on."),
      },
    ],
    usChoices: [
      {
        id: "us-hold-2011",
        label: "Hold the rail",
        summary: "No perp walk for a system.",
        kind: "ignore",
        historical: true,
        deltas: { street: -4, media: -4, my_party: 4 },
      },
      {
        id: "us-file-upstairs",
        label: "File upstairs",
        summary: "Treat the factory like Keating.",
        kind: "hard",
        deltas: { street: 8, media: 8, irgc: -6, saudis: -8 },
        ...hindsight("You filed upstairs. The dock was not empty. History left it empty. You have the point. The book continues on."),
      },
    ],
    sources: ["FCIC report 2011", "S&L vs 2008 prosecution comparison"],
    visibleFactions: ROOM,
    next: null,
  },
  {
    id: "three-six-three",
    year: 1966,
    yearLabel: "1966",
    title: "3-6-3",
    era: "sl",
    status: "playable",
    secret: true,
    referee: {
      paragraphs: [
        "Borrow at 3. Lend at 6. On the golf course by 3. This is the world Volcker is about to kill. The cubicle is a teller window. The invoice is a house someone lives in.",
      ],
      tags: ["LT", "AL"],
    },
    briefings: [
      {
        faction: "irgc",
        audience: "iran",
        rant: "The book is a mortgage. Drive to it and a family opens the door. That will not last.",
      },
    ],
    situation: "The boring bank. You can stay here. History will not.",
    iranChoices: [
      {
        id: "ir-stay-363",
        label: "Stay boring",
        summary: "Golf at 3.",
        kind: "walk",
        deltas: {},
        ending: "boring_bank",
      },
      {
        id: "ir-back-1979",
        label: "Forward to 1979",
        summary: "The hike is coming.",
        kind: "hard",
        historical: true,
        deltas: {},
        nextCard: "volcker-1979",
      },
    ],
    usChoices: [
      {
        id: "us-stay-363",
        label: "Leave the thrifts alone",
        summary: "Regulation Q.",
        kind: "walk",
        deltas: {},
        ending: "boring_bank",
      },
      {
        id: "us-back-1979",
        label: "Forward to 1979",
        summary: "Volcker is coming.",
        kind: "hard",
        historical: true,
        deltas: {},
        nextCard: "volcker-1979",
      },
    ],
    sources: ["3-6-3 rule of thumb"],
    visibleFactions: ["irgc", "street", "cia"],
    next: "volcker-1979",
  },
];

const BY_ID = new Map(CARDS.map((c) => [c.id, c]));

export function cardById(id: string): Card | undefined {
  return BY_ID.get(id);
}

export function playableCards(): readonly Card[] {
  return CARDS.filter((c) => !c.secret);
}

export { CARDS };
